name: Enforce Commit Author

on:
  push:
    branches: ["**"]
  pull_request:
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Verify no disallowed authors in commit range
        run: |
          set -euo pipefail
          # Determine commit range
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            RANGE="${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }}"
          else
            RANGE="${{ github.event.before }}..${{ github.sha }}"
          fi
          echo "Checking range: $RANGE"
          emails=$(git log --format='%ae%n%ce' $RANGE || true)
          echo "Authors/Committers in range:"; echo "$emails" | sed '/^$/d' | sort -u
          # Blocklist specific bad identities only; allow bots and collaborators
          if echo "$emails" | rg -qi '^greg@siteorigin\.com$'; then
            echo 'Found disallowed email: greg@siteorigin.com' >&2
            exit 1
          fi
          echo 'Author check passed.'
